# Generated by Django 5.2 on 2025-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='empreendor',
            new_name='empreendedor',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='longitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
    ]
