# Generated by Django 5.2 on 2025-05-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_endereco_cidade_endereco_uf_delete_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='uf',
        ),
    ]
