# Generated by Django 5.2 on 2025-05-04 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_endereco_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='empreendedor',
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa'),
        ),
    ]
