# Generated by Django 5.2 on 2025-05-04 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_endereco_empreendedor_endereco_pessoa'),
        ('usuarios', '0004_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
