# Generated by Django 5.2 on 2025-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_endereco_pessoa_endereco_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, null=True, verbose_name='Telefone'),
        ),
    ]
