# Generated by Django 5.2 on 2025-05-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_empreendedor_descricao_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.CharField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='longitude',
            field=models.CharField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
