# Generated by Django 5.2 on 2025-05-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cidade_pessoa_cliente_empreendedor_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='empreendedor',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='empreendor',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empreendedor',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
