# Generated by Django 5.2 on 2025-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_endereco_cidade_remove_cliente_pessoa_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto Usuário'),
        ),
    ]
